### ISSUE TITLE
groupIcdToCCS 訊息修正

### ISSUE THREAD

**Issue by yijutseng** [DHLab-CGU/emr#10]
` test<-groupIcdToCCS(IBDCaseAllIcdAllData,MemberID,Icd,DateServiceStarted,"2015-10-01",F)`
出現
`'icd_' prefixed functions have been replaced with either ICD-9 or ICD-10 specific functions, which have an 'icd9_' or 'icd10_' prefix, or lost their prefix altogether. `

可重現錯誤的檔案
https://drive.google.com/file/d/1KsE__vpFPv1OJv79goLevCj9z5i87dq-/view

這個message是否可以把對不到的清單取不重複列出前十個，確保訊息清楚: 
`Warning message:
NA means icd code does not match the format.`

**Comment by amamagg** [comment]
改好了, 一並新增其他功能的warning msg
commit a5564995c6255574d8fab329510933610961bbeb

**Comment by yijutseng** [comment]
最後一句話看能不能改得清楚一點，
首先_warning ICD_:Warning message: 的_warning ICD_好像是多的？
然後突然出現NA好像也不清楚，看是否能改成
The ICD mentioned above matches to "NA" due to the format or other issues.

`warning ICD: 642.92	
warning ICD: 654.70	
warning ICD:Warning message:
'NA' means the data does not match the format `

**Comment by amamagg** [comment]
改好了
commit 616dead9dc065dee353f895c4083e72759fd376c
