### ISSUE TITLE
增加兩個功能

### ISSUE THREAD

**Issue by yijutseng** [DHLab-CGU/emr#12]
參考https://github.com/DHLab-CGU/DHAnalysis/blob/master/R/groupICDBasedOnGrep.R
除了輸入關鍵字外，也提供輸入一個 icd csv清單，然後基於這個清單做grouping的功能

https://github.com/DHLab-CGU/DHAnalysis/blob/master/R/selectCasesBasedOnFactIcdList.R
篩選Case的功能，例如255.0，出現至少兩次，輸入後會輸出符合條件的case

**Comment by amamagg** [comment]
1.篩選Case的功能，例如255.0，出現至少兩次，輸入後會輸出符合條件的case
目前function name暫取這個 **selectCases**
commit b7565685326198897b85ee36ff8a450a8386e0d5

**Comment by yijutseng** [comment]
https://dhlab-cgu.github.io/emr/reference/selectCases.html
範例請提供挑得出case的範例

**Comment by amamagg** [comment]
之前都忘記一起更新網頁版...新的commit就看得到了~
commit f6837f1dfd3f79aba3cf5adc66a82727709afab0
```
selectCases("^785", sampleDxFile, ID, ICD, Date, 2)
#>    ID firstCaseDate endCaseDate count   period MostCommonICD MostCommonICDCount
#> 1:  A    2008-05-03  2009-03-02     2 303 days         785.1                  1
#> 2:  B    2008-01-19  2008-04-07     2  79 days        785.52                  1
```

**Comment by yijutseng** [comment]
範例也要提供`sampleDxFile`

**Comment by amamagg** [comment]
commit 136243bcf38afa48429ab040a5912545f43abe13
