### ISSUE TITLE
安裝套件時的錯誤訊息

### ISSUE THREAD

**Issue by yijutseng** [DHLab-CGU/emr#14]
** testing if installed package can be loaded
Error: package or namespace load failed for ‘emr’ in namespaceExport(ns, exports):
 undefined exports: groupIcdToCustomGrep
Error: loading failed
Execution halted
ERROR: loading failed

**Comment by amamagg** [comment]
改好了, 先拿掉 groupIcdToCustomGrep 這個function, 等改好再上傳
commit f82f7b68a152b191477fe8db74b317bd6789fd90
