### ISSUE TITLE
IcdDxToCustomGrep.R 的相關問題

### ISSUE THREAD

**Issue by yijutseng** [DHLab-CGU/emr#18]
Code顯示功能是用窮舉法且要完全相同的字串才能正確比對，但grep的含意為global search regular expression，這邊有部份比對的意思，應保留此功能，但改名成IcdDxToCustom，然後另外做一個新功能"IcdDxToCustomGrep"，是部份比對。

部份比對的對照表範例:
Renal,^585|^586|^996.73|^996.81|^V42.0|^V45.1 
Lymphoma,^200|^201|^202

以Lymphoma來說，200.0、200.10、201.22等code都應該被歸為Lymphoma

**Comment by amamagg** [comment]
改好名字了
commit dd91d776968480c3c76d37664134a2962f271cd5
