### ISSUE TITLE
安裝錯誤，‘PheWAS’ 相關

### ISSUE THREAD

**Issue by yijutseng** [DHLab-CGU/emr#2]
安裝時出現錯誤，需調整
`ERROR: dependency ‘PheWAS’ is not available for package ‘emr’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/emr’
Installation failed: Command failed (1)`

**Comment by yijutseng** [comment]
先用
`devtools::install_github("PheWAS/PheWAS")`
安裝PheWAS後，再裝emr就沒問題，不過要是要用的話，應該要在安裝emr時直接安裝PheWAS?

**Comment by amamagg** [comment]
commit: bdfdfcd3f11b26fbb92560d47fd7d7ce04de6ebb
後來發現沒用到PheWAS的東西就先移除了XD
之前phecode的資料是直接從phewas網站抓下來的
