### ISSUE TITLE
IcdDxToCCS對應有誤

### ISSUE THREAD

**Issue by yijutseng** [DHLab-CGU/emr#20]
程式碼如下，測試資料在google drive，測試發現同樣的ICD有不同的CCS。

`FactIcdMomCCS<-readRDS("FactIcdMomCCS.rds")`
`FactIcdMomCCS$CCSCate<-IcdDxToCCS(FactIcdMomCCS,FinalID,Icd,DateServiceStarted,"2015/10/01")`
`FactIcdMomCCS<-data.table(FactIcdMomCCS)`
`FactIcdMomCCS[Icd=="654.70"] `

**Comment by amamagg** [comment]
commit 136243bcf38afa48429ab040a5912545f43abe13
最新版本已改善這個問題
