### ISSUE TITLE
Warning messages顯示方式修改

### ISSUE THREAD

**Issue by yijutseng** [DHLab-CGU/emr#21]
原來的warning message太長了，不太好閱讀，可能要作修正。而且哪些碼出現幾次的資訊也應該要提供。

`wrong Format: 070.4	
wrong Format: V61	
wrong Format: 799	
wrong Format: V25.1	
wrong Format: V72.6	
wrong Format: 780.6	
wrong Format: 793.1	
wrong Format: 284.1	
wrong Format: 726.1	
wrong Format: 275.0	
wrong Format: 274.0	
wrong Format: 599.7	
wrong Format: 786.3	
wrong Format: 173.6	
wrong Format: 173.3	
wrong Format: 453.8	
wrong Format: 173.1	
wrong Format: 724.0	
wrong Format: 611.8	
wrong Format: 173.5	
wrong Format: 795.5	
wrong Format: 173.4	
wrong Format: 279.4	
wrong Format: 512.8	
wrong Format: 571.4	
wrong Format: 348.8	
wrong Format: 173.0	
wrong Format: 596.8	
wrong Format: 787.6	
wrong Format: 998.3	
wrong Format: 173.7	
wrong Format: 286.5	
wrong Format: 784.5	
wrong Format: 866.0	
wrong Format: 250.0	
wrong Format: 276.6	
wrong Format: V12.2	
wrong Format: 206.0	
wrong Format: 368.1	
wrong Format: V28.8	
wrong Format: 726.9	
wrong Format: 550.9	
wrong Format: 041.0	
wrong Format: 518.5	
wrong Format: 304.0	
wrong Format: 686.0	
wrong Format: 173.8	
wrong Format: 969.7	
wrong Format: 799.2	
wrong Format: 173.9	
wrong Format: 715.9	
wrong Format: 346.2	
wrong Format: V53.5	
wrong Format: 425.1	
wrong Format: 296.3	
wrong Format: 239.8	
wrong Format: 823.0	
wrong Format: 511	
wrong Format: 511.8	
wrong Format: 038.1	
wrong Format: 287.4	
wrong Format: 309	
wrong Format: 250.1	
wrong Format: 346.9	
wrong Format: 969.0	
wrong Format: 288.0	
wrong Format: 795.1	
wrong Format: 959.1	
wrong Format: 789.0	
wrong Format: 750	
wrong Format: 799.0	
wrong Format: 482.4	
wrong Format: 733.0	
wrong Format: 480	
wrong Format: 571	
wrong Format: 174	
wrong Format: 516.3	
wrong Format: 296.9	
wrong Format: 294.1	
wrong Format: 997.4	
wrong Format: 041.1	
wrong Format: 173.2	
wrong Format: 070.5	
wrong Format: 295.7	
wrong Format: 250.6	
wrong Format: 518.8	
wrong Format: 722.1	
wrong Format: 998	
wrong Format: 296.8	
wrong Format: 093	
wrong Format: 599	
wrong Format: 367.2	
wrong Format: 494	
wrong Format: 631	
wrong Format: 730.2	
wrong Format: 091	
wrong Format: 011.9	
wrong Format: 641	
wrong Format: 998.0	
wrong Format: 583	
wrong Format: 824	
wrong Format: 250	
wrong Format: 530.1	
wrong Format: 305.0	
wrong Format: 711.0	
wrong Format: 780.9	
wrong Format: 726	
wrong Format: 569	
wrong Format: 780.3	
wrong Format: 304	
wrong Format: 779.3	
wrong Format: 202.8	
wrong Format: 852.2	
wrong Format: 786.5	
wrong Format: 175	
wrong Format: 296.6	
wrong Format: 300.0	
wrong Format: 296.2	
wrong Format: 999.6	
wrong Format: 791	
wrong Format: 786.0	
wrong Format: 342.9	
wrong Format: V72.3	
wrong Format: 384.0	
wrong Format: 999	
wrong Format: 304.1	
wrong Format: 370.4	
wrong Format: 391	
wrong Format: 307.2	
wrong Format: 303.9	
wrong Format: 425	
wrong Format: 801	
wrong Format: V23.8	
wrong Format: 301.1	
wrong Format: 300.1	
wrong Format: 493.9	
wrong Format: 532.9	
wrong Format: 304.8	
wrong Format: 355	
wrong Format: 729.3	
wrong Format: 787.0	
wrong Format: 296.5	
wrong Format: 846	
wrong Format: 380.1	
wrong Format: 564.0	
wrong Format: 718.9	
wrong Format: 444.0	
wrong Format: 724	
wrong Format: 395	
wrong Format: 300	
wrong Format: 603	
wrong Format: V26.2	
wrong Format: 530.8	
wrong Format: 970.8	
wrong Format: 392	
wrong Format: 381	
wrong Format: 464.0	
wrong Format: 204.1	
wrong Format: 584	
wrong Format: 963	
wrong Format: 521.0	
wrong Format: 070.3	
wrong Format: 996.9	
wrong Format: 309.8	
wrong Format: 789.3	
wrong Format: E888	
wrong Format: 284.8	
wrong Format: 535.4	
wrong Format: 720	
wrong Format: 054	
wrong Format: 041.4	
wrong Format: 404	
wrong Format: 454	
wrong Format: 300.2	
wrong Format: V40	
wrong Format: 842.0	
wrong Format: 402.0	
wrong Format: 719.5	
wrong Format: 466	
wrong Format: 789.5	
wrong Format: 535.5	
wrong Format: 361.1	
wrong Format: 768.7	
wrong Format: 531.9	
wrong Format: 367	
wrong Format: 493	
wrong Format: 195	
wrong Format: 728.7	
wrong Format: 535	
wrong Format: 346.8	
wrong Format: 574.0	
wrong Format: 231	
wrong Format: 790.0	
wrong Format: 948	
wrong Format: 741.9	
wrong Format: 762	
wrong Format: 461	
wrong Format: 902.8	
wrong Format: 401	
wrong Format: 708	
wrong Format: 999.5	
wrong Format: V16	
wrong Format: 765.1	
wrong Format: 719.4	
wrong Format: V72	
wrong Format: 578	
wrong Format: 996.8	
wrong Format: 790	
wrong Format: 574	
wrong Format: 823.1	
wrong Format: 474.0	
wrong Format: 715.1	
wrong Format: 854.0	
wrong Format: 960	
wrong Format: 946	
wrong Format: 411	
wrong Format: 747.3	
wrong Format: 282.6	
wrong Format: 366.1	
wrong Format: 619	
wrong Format: 305.5	
wrong Format: V13.8	
wrong Format: 682	
wrong Format: 873	
wrong Format: 616.1	
wrong Format: 165	
wrong Format: 730.1	
wrong Format: E819	
wrong Format: 832	
wrong Format: 788.2	
wrong Format: 998.1	
wrong Format: 440.2	
wrong Format: 722.9	
wrong Format: 292	
wrong Format: 601	
wrong Format: 592	
wrong Format: 295	
wrong Format: 569.8	
wrong Format: 303.0	
wrong Format: 396	
wrong Format: 715	
wrong Format: 793.8	
wrong Format: 365	
wrong Format: V72.8	
wrong Format: 567.2	
wrong Format: V76	
wrong Format: 723	
wrong Format: 366	
wrong Format: 362.4	
wrong Format: 924.2	
wrong Format: 216	
wrong Format: 250.9	
wrong Format: 524.6	
wrong Format: 151	
wrong Format: V45.6	
wrong Format: 707.1	
wrong Format: 780	
wrong Format: V54.8	
wrong Format: 786	
wrong Format: 282.4	
wrong Format: 627	
wrong Format: V85.4	
wrong Format: 839.0	
wrong Format: 865.0	
wrong Format: 752.3	
wrong Format: 131	
wrong Format: 051	
wrong Format: 438	
wrong Format: 428	
wrong Format: V10.9	
wrong Format: 716.4	
wrong Format: 743	
wrong Format: 250.5	
wrong Format: 634.9	
wrong Format: 753.1	
wrong Format: 304.4	
wrong Format: 780.7	
wrong Format: 345.4	
wrong Format: 716.9	
wrong Format: V09	
wrong Format: 550	
wrong Format: 155	
wrong Format: 239	
wrong Format: 331.1	
wrong Format: 784.9	
wrong Format: 099	
wrong Format: V54	
wrong Format: 176	
wrong Format: 280	
wrong Format: 535.1	
wrong Format: 726.3	
wrong Format: V25	
wrong Format: 793	
wrong Format: 621.3	
wrong Format: 373.3	
wrong Format: 782	
wrong Format: 488	
wrong Format: 727.4	
wrong Format: 844	
wrong Format: 722.3	
wrong Format: 845.0	
wrong Format: 278.0	
wrong Format: 274.8	
wrong Format: 997.0	
wrong Format: 722	
wrong Format: 376.1	
wrong Format: 874.0	
wrong Format: 414.0	
wrong Format: 721	
wrong Format: 342	
wrong Format: 722.7	
wrong Format: 482	
wrong Format: 236.9	
wrong Format: 690	
wrong Format: 822	
wrong Format: 189	
wrong Format: 362.1	
wrong Format: 799.8	
wrong Format: 282	
wrong Format: 012	
wrong Format: 569.6	
wrong Format: V40.3	
wrong Format: 622.1	
wrong Format: 755.5	
wrong Format: 842	
wrong Format: 553.0	
wrong Format: 617	
wrong Format: 780.0	
wrong Format: 789.6	
wrong Format: 790.9	
wrong Format: 525.2	
wrong Format: 200.1	
wrong Format: 996.7	
wrong Format: 208.0	
wrong Format: 403.9	
wrong Format: 364.0	
wrong Format: 371.3	
wrong Format: 722.5	
wrong Format: 385.0	
wrong Format: 259	
wrong Format: 794.3	
wrong Format: 839.2	
wrong Format: 744	
wrong Format: 733	
wrong Format: 572	
wrong Format: 372.2	
wrong Format: 310.8	
wrong Format: V58.6	
wrong Format: 275	
wrong Format: V04.8	
wrong Format: 795.7	
wrong Format: 702.1	
wrong Format: 346.1	
wrong Format: 804.9	
wrong Format: 372.3	
wrong Format: 070	
wrong Format: V70	
wrong Format: 304.9	
wrong Format: 787.9	
wrong Format: 809	
wrong Format: 312.8	
wrong Format: 590.8	
wrong Format: 823.8	
wrong Format: V30.0	
wrong Format: 726.7	
wrong Format: V67.0	
wrong Format: 402.9	
wrong Format: 242.9	
wrong Format: 640.0	
wrong Format: 130	
wrong Format: 332	
wrong Format: 562.1	
wrong Format: 826	
wrong Format: 718.3	
wrong Format: 573	
wrong Format: 305	
wrong Format: 832.1	
wrong Format: 309.2	
wrong Format: 813.0	
wrong Format: 812.0	
wrong Format: 823.9	
wrong Format: 798	
wrong Format: 442	
wrong Format: 516	
wrong Format: 711.3	
wrong Format: 692.7	
wrong Format: 363	
wrong Format: 314.0	
wrong Format: 727	
wrong Format: 562	
wrong Format: 574.5	
wrong Format: 733.9	
wrong Format: 550.1	
wrong Format: 831.0	
wrong Format: 348.3	
wrong Format: 255	
wrong Format: 840	
wrong Format: 743.0	
wrong Format: 438.4	
wrong Format: 714	
wrong Format: 814.1	
wrong Format: 345.5	
wrong Format: 1wrong ICD version: 296.22	
wrong ICD version: 799.9	
wrong ICD version: 719.45	
wrong ICD version: L03.115	
wrong ICD version: F32.9	
wrong ICD version: F28	
wrong ICD version: L03.113	
wrong ICD version: F33.2	
wrong ICD version: T80.211A	
wrong ICD version: 724.2	
wrong ICD version: E11.43	
wrong ICD version: 174.9	
wrong ICD version: K92.1	
wrong ICD version: I50.31	
wrong ICD version: J18.9	
wrong ICD version: K12.31	
wrong ICD version: 300.00	
wrong ICD version: O36.5930	
wrong ICD version: A40.1	
wrong ICD version: F11.23	
wrong ICD version: 309.0	
wrong ICD version: N17.9	
wrong ICD version: 724.4	
wrong ICD version: K91.89	
wrong ICD version: B19.21	
wrong ICD version: F10.20	
wrong ICD version: S72.141A	
wrong ICD version: K80.64	
wrong ICD version: I48.4	
wrong ICD version: F32.2	
wrong ICD version: B10.09	
wrong ICD version: C22.9	
wrong ICD version: 202.80	
wrong ICD version: I35.0	
wrong ICD version: I12.9	
wrong ICD version: I48.91	
wrong ICD version: R10.84	
wrong ICD version: I50.23	
wrong ICD version: 591	
wrong ICD version: T87.81	
wrong ICD version: M17.12	
wrong ICD version: S42.202A	
wrong ICD version: B18.2	
wrong ICD version: K70.31	
wrong ICD version: C78.7	
wrong ICD version: N39.0	
wrong ICD version: I63.9	
wrong ICD version: I21.4	
wrong ICD version: A41.9	
wrong ICD version: J96.01	
wrong ICD version: K43.0	
wrong ICD version: D46.Z	
wrong ICD version: F10.239	
wrong ICD version: N00.8	
wrong ICD version: A41.4	
wrong ICD version: Z51.11	
wrong ICD version: K74.69	
wrong ICD version: 892.1	
wrong ICD version: C92.02	
wrong ICD version: S82.842A	
wrong ICD version: 304.00	
wrong ICD version: 309.28	
wrong ICD version: T86.19	
wrong ICD version: Z51.89	
wrong ICD version: S72.141D	
wrong ICD version: I61.4	
wrong ICD version: B25.8	
wrong ICD version: I95.1	
wrong ICD version: T86.49	
wrong ICD version: J69.0	
wrong ICD version: G92	
wrong ICD version: V81.0	
wrong ICD version: J44.9	
wrong ICD version: L02.414	
wrong ICD version: A07.2	
wrong ICD version: 312.89	
wrong ICD version: 576.1	
wrong ICD version: T84.51XA	
wrong ICD version: T85.598A	
wrong ICD version: K92.2	
wrong ICD version: J40	
wrong ICD version: I60.11	
wrong ICD version: 799.3	
wrong ICD version: K74.60	
wrong ICD version: M43.02	
wrong ICD version: A41.52	
wrong ICD version: 296.33	
wrong ICD version: I12.0	
wrong ICD version: 719.44	
wrong ICD version: I61.5	
wrong ICD version: E86.0	
wrong ICD version: E11.22	
wrong ICD version: M43.15	
wrong ICD version: 296.32	
wrong ICD version: G40.409	
wrong ICD version: K65.0	
wrong ICD version: 303.90	
wrong ICD version: R07.89	
wrong ICD version: J44.1	
wrong ICD version: M62.81	
wrong ICD version: R53.81	
wrong ICD version: 739.1	
wrong ICD version: F25.9	
wrong ICD version: 300.02	
wrong ICD version: T21.04XD	
wrong ICD version: E11.621	
wrong ICD version: T86.11	
wrong ICD version: L97.113	
wrong ICD version: 722.90	
wrong ICD version: G20	
wrong ICD version: M86.9	
wrong ICD version: Z48.815	
wrong ICD version: K26.0	
wrong ICD version: R26.2	
wrong ICD version: E11.622	
wrong ICD version: S02.42XA	
wrong ICD version: C48.1	
wrong ICD version: D71	
wrong ICD version: F31.9	
wrong ICD version: F11.29	
wrong ICD version: S06.5X9D	
wrong ICD version: 308.0	
wrong ICD version: E860	
wrong ICD version: K83.1	
wrong ICD version: I25.10	
wrong ICD version: F10.231	
wrong ICD version: E11.9	
wrong ICD version: N13.30	
wrong ICD version: A40.3	
wrong ICD version: S32.402D	
wrong ICD version: N19	
wrong ICD version: N30.01	
wrong ICD version: R26.9	
wrong ICD version: F10.120	
wrong ICD version: S72.002A	
wrong ICD version: M48.02	
wrong ICD version: 272.4	
wrong ICD version: C22.0	
wrong ICD version: I50.9	
wrong ICD version: K72.90	
wrong ICD version: 296.56	
wrong ICD version: D57.02	
wrong ICD version: 079.99	
wrong ICD version: Z94.4	
wrong ICD version: 070.54	
wrong ICD version: 309.81	
wrong ICD version: 696.0	
wrong ICD version: 314.01	
wrong ICD version: 296.30	
wrong ICD version: E11.649	
wrong ICD version: M17.11	
wrong ICD version: E883	
wrong ICD version: E890	
wrong ICD version: E869	
wrong ICD version: M06.9	
wrong ICD version: M51.24	
wrong ICD version: E66.9	
wrong ICD version: G95.0	
wrong ICD version: E78.5	
wrong ICD version: J96.00	
wrong ICD version: 728.87	
wrong ICD version: C34.90	
wrong ICD version: B20	
wrong ICD version: F10.230	
wrong ICD version: I82.611	
wrong ICD version: F11.20	
wrong ICD version: L89.222	
wrong ICD version: M62.82	
wrong ICD version: K76.6	
wrong ICD version: G93.40	
wrong ICD version: D61.810	
wrong ICD version: C01	
wrong ICD version: O98.42	
wrong ICD version: R18.8	
wrong ICD version: F13.20	
wrong ICD version: D64.9	
wrong ICD version: N17.0	
wrong ICD version: J95.821	
wrong ICD version: K82.3	
wrong ICD version: I50.33	
wrong ICD version: I31.8	
wrong ICD version: E87.1	
wrong ICD version: K76.7	
wrong ICD version: E43	
wrong ICD version: D62	
wrong ICD version: D61.818	
wrong ICD version: 593.4	
wrong ICD version: N18.6	
wrong ICD version: F05	
wrong ICD version: R64	
wrong ICD version: I69.354	
wrong ICD version: J91.8	
wrong ICD version: I81	
wrong ICD version: E87.2	
wrong ICD version: I82.532	
wrong ICD version: G93.41	
wrong ICD version: I48.92	
wrong ICD version: I25.810	
wrong ICD version: J81.0	
wrong ICD version: I10	
wrong ICD version: B17.9	
wrong ICD version: 682.7	
wrong ICD version: R91.8	
wrong ICD version: E46	
wrong ICD version: C79.51	
wrong ICD version: I69.359	
wrong ICD version: Z68.41	
wrong ICD version: R65.11	
wrong ICD version: M86.171	
wrong ICD version: E11.8	
wrong ICD version: A07.1	
wrong ICD version: D65	
wrong ICD version: G93.5	
wrong ICD version: C91.10	
wrong ICD version: J96.90	
wrong ICD version: J96.91	
wrong ICD version: 719.7	
wrong ICD version: R57.1	
wrong ICD version: D68.51	
wrong ICD version: J96.02	
wrong ICD version: A41.89	
wrong ICD version: C79.00	
wrong ICD version: G21.0	
wrong ICD version: B95.7	
wrong ICD version: D67	
wrong ICD version: I62.00	
wrong ICD version: K75.0	
wrong ICD version: 739.2	
wrong ICD version: F17.200	
wrong ICD version: E11.65	
wrong ICD version: B02.29	
wrong ICD version: 300.4	
wrong ICD version: C83.30	
wrong ICD version: F02.80	
wrong ICD version: K86.1	
wrong ICD version: R91.1	
wrong ICD version: Z99.81	
wrong ICD version: G93.6	
wrong ICD version: G89.29	
wrong ICD version: M32.9	
wrong ICD version: G31.83	
wrong ICD version: N13.8	
wrong ICD version: M15.9	
wrong ICD version: J96.21	
wrong ICD version: 787.03	
wrong ICD version: 401.9	
wrong ICD version: D63.8	
wrong ICD version: 571.5	
wrong ICD version: 296.20	
wrong ICD version: 314.00	
wrong ICD version: 723.1	
wrong ICD version: R26.81	
wrong ICD version: K91.840	
wrong ICD version: E849	
wrong ICD version: E854	
wrong ICD version: Z00.00	
wrong ICD version: M99.03	
wrong ICD version: L60.0	
wrong ICD version: 781.2	
wrong ICD version: C79.31	
wrong ICD version: L03.114	
wrong ICD version: B19.20	
wrong ICD version: R45.851	
wrong ICD version: A41.81	
wrong ICD version: G82.20	
wrong ICD version: K76.0	
wrong ICD version: Z91.14	
wrong ICD version: F31.30	
wrong ICD version: B00.4	
wrong ICD version: C78.00	
wrong ICD version: D69.59	
wrong ICD version: I25.2	
wrong ICD version: E11.42	
wrong ICD version: I85.10	
wrong ICD version: J96.20	
wrong ICD version: 584.9	
wrong ICD version: I47.1	
wrong ICD version: F03.90	
wrong ICD version: D68.9	
wrong ICD version: D69.6	
wrong ICD version: I50.22	
wrong ICD version: I95.89	
wrong ICD version: K80.01	
wrong ICD version: I13.2	
wrong ICD version: K56.7	
wrong ICD version: K90.0	
wrong ICD version: R09.2	
wrong ICD version: K21.9	
wrong ICD version: R65.21	
wrong ICD version: V58.62	
wrong ICD version: R47.02	
wrong ICD version: G95.29	
wrong ICD version: I69.391	
wrong ICD version: I82.509	
wrong ICD version: B95.4	
wrong ICD version: R65.20	
wrong ICD version: I95.9	
wrong ICD version: J84.9	
wrong ICD version: I50.32	
wrong ICD version: G82.50	
wrong ICD version: F10.99	
wrong ICD version: E15	
wrong ICD version: K22.0	
wrong ICD version: K31.1	
wrong ICD version: 304.30	
wrong ICD version: R26.0	
wrong ICD version: 739.3	
wrong ICD version: S91.301S	
wrong I

Warning messages:
1: The ICD mentioned above matches to "NA" due to the format or other issues. 
2: "wrong Format" means the ICD has wrong format 
3: "wrong ICD version" means the ICD classify to wrong ICD version (cause the "icd10usingDate" or other issues) `

**Comment by amamagg** [comment]
commit d6380483d4f4b67911902fc122cae03702c8df47
```
> sampleDxFile$Short <- IcdDxDecimalToShort(sampleDxFile,ICD,Date,"2015/10/01")$ICD
#> wrong ICD Format: total 13 ICD codes (the number of occurrences is in brackets)
#> c("E78.0 (8)", "M79.1 (8)", "Z22.52 (7)", "A04.7 (6)", "Z98.89 (4)", "E78.4 (3)", "M50.32 (2)", "123.45 (1)", "H34.832 (1)", "M48.06 (1)")
#> 	
#> wrong ICD version: total 4 ICD codes (the number of occurrences is in brackets)
#> c("A01.05 (1)", "E03.0 (1)", "A0105 (1)", "42761 (1)")
#> 	
#> Warning: The ICD mentioned above matches to "NA" due to the format or other issues.
#> Warning: "wrong Format" means the ICD has wrong format
#> Warning: "wrong ICD version" means the ICD classify to wrong ICD version (cause the "icd10usingDate" or other issues)
```

**Comment by yijutseng** [comment]
大小寫還是注意一下，**W**rong **f**ormat

**Comment by amamagg** [comment]
commit 136243bcf38afa48429ab040a5912545f43abe13
已修正大小寫
