### ISSUE TITLE
IcdDxToCCS錯誤訊息優化

### ISSUE THREAD

**Issue by yijutseng** [DHLab-CGU/emr#23]
(可之後慢慢處理，不發會忘記@@)

是否可比照之前討論的錯誤訊息辦理? (AHRQ等?)

`HepCAllDiagCCS<-emr::IcdDxToCCS(HepCAllDiag,IndividualId,Icd,DateServiceStarted,"2015/10/01")
wrong ICD Format: total 1280 ICD codes (the number of occurrences is in brackets)
c("E78.0 (28480)", "M79.1 (25249)", "M48.06 (21063)", "E78.4 (15015)", "284.1 (14848)", "Z22.52 (14307)", "I27.2 (11051)", "Z98.89 (10576)", "A04.7 (8697)", "T81.4XXA (7221)")
	
wrong ICD version: total 508 ICD codes (the number of occurrences is in brackets)
c("799.9 (28107)", "N17.9 (886)", "N18.6 (589)", "E11.9 (519)", "B19.20 (498)", "I12.0 (458)", "J96.01 (405)", "A41.9 (340)", "I25.10 (318)", "N39.0 (293)")
	
Warning messages:
1: The ICD mentioned above matches to "NA" due to the format or other issues. 
2: "wrong Format" means the ICD has wrong format 
3: "wrong ICD version" means the ICD classify to wrong ICD version (cause the "icd10usingDate" or other issues) `

**Comment by amamagg** [comment]
已更新~
commit 419a2c1f8e894216342308022780d8b6a7a7ba67
