### ISSUE TITLE
condition era功能與預期有落差

### ISSUE THREAD

**Issue by yijutseng** [DHLab-CGU/emr#27]
目前的功能只能知道起始日結束日以及整個區間內有幾個era，
但是預期功能是應有每個人每個era的起始日結束日。
`era <- 
  getConditionEra(sampleDxFile, ID, ICD, 
                  Date, "2015-10-01", 
                  ccs, isDescription=FALSE)`

如果只看A10

`> era[ID=="A10"]
    ID CCS_CATEGORY firstCaseDate endCaseDate count era    period
1: A10          158    2007-11-04  2012-07-30     5   4 1730 days`

呈現有五個診斷，４個era，但應該要呈現
ID era ...
A10 1
A10 2
A10 3
A10 4

**Comment by amamagg** [comment]
commit 5eb8250
改好了~
