### ISSUE TITLE
安裝時出現Warning，有些套件使用一樣的function名，這樣會有問題

### ISSUE THREAD

**Issue by yijutseng** [DHLab-CGU/emr#3]
Warning: replacing previous import ‘data.table::first’ by ‘dplyr::first’ when loading ‘emr’
Warning: replacing previous import ‘data.table::between’ by ‘dplyr::between’ when loading ‘emr’
Warning: replacing previous import ‘data.table::last’ by ‘dplyr::last’ when loading ‘emr’
Warning: replacing previous import ‘data.table::month’ by ‘lubridate::month’ when loading ‘emr’
Warning: replacing previous import ‘data.table::hour’ by ‘lubridate::hour’ when loading ‘emr’
Warning: replacing previous import ‘dplyr::intersect’ by ‘lubridate::intersect’ when loading ‘emr’
Warning: replacing previous import ‘data.table::quarter’ by ‘lubridate::quarter’ when loading ‘emr’
Warning: replacing previous import ‘data.table::week’ by ‘lubridate::week’ when loading ‘emr’
Warning: replacing previous import ‘data.table::year’ by ‘lubridate::year’ when loading ‘emr’
Warning: replacing previous import ‘dplyr::union’ by ‘lubridate::union’ when loading ‘emr’
Warning: replacing previous import ‘data.table::wday’ by ‘lubridate::wday’ when loading ‘emr’
Warning: replacing previous import ‘data.table::second’ by ‘lubridate::second’ when loading ‘emr’
Warning: replacing previous import ‘dplyr::setdiff’ by ‘lubridate::setdiff’ when loading ‘emr’
Warning: replacing previous import ‘data.table::minute’ by ‘lubridate::minute’ when loading ‘emr’
Warning: replacing previous import ‘data.table::mday’ by ‘lubridate::mday’ when loading ‘emr’
Warning: replacing previous import ‘data.table::yday’ by ‘lubridate::yday’ when loading ‘emr’
Warning: replacing previous import ‘data.table::isoweek’ by ‘lubridate::isoweek’ when loading ‘emr’
Warning: replacing previous import ‘dplyr::failwith’ by ‘plyr::failwith’ when loading ‘emr’
Warning: replacing previous import ‘dplyr::id’ by ‘plyr::id’ when loading ‘emr’
Warning: replacing previous import ‘dplyr::summarize’ by ‘plyr::summarize’ when loading ‘emr’
Warning: replacing previous import ‘dplyr::count’ by ‘plyr::count’ when loading ‘emr’
Warning: replacing previous import ‘dplyr::desc’ by ‘plyr::desc’ when loading ‘emr’
Warning: replacing previous import ‘dplyr::mutate’ by ‘plyr::mutate’ when loading ‘emr’
Warning: replacing previous import ‘dplyr::arrange’ by ‘plyr::arrange’ when loading ‘emr’
Warning: replacing previous import ‘dplyr::rename’ by ‘plyr::rename’ when loading ‘emr’
Warning: replacing previous import ‘lubridate::here’ by ‘plyr::here’ when loading ‘emr’
Warning: replacing previous import ‘dplyr::summarise’ by ‘plyr::summarise’ when loading ‘emr’

**Comment by amamagg** [comment]
commit a70846dc04b625b24a373275c37e27c14f53b03f

移除import data.table package, 修改有使用data.table fun的code (getConditionEra.R)
