### ISSUE TITLE
Flagged correct ICD10-CM as wrong

### ISSUE THREAD

**Issue by Kuroshiwo** [DHLab-CGU/emr#35]
R> ## ICD to uniform short format
R> 
R> ICD_Short <- icdDxDecimalToShort(dxDataFile = sampleDxFile,
+                                  icdColName = ICD,
+                                  dateColName = Date, 
+                                  icd10usingDate = "2015/10/01")
Wrong ICD format: total 68 ICD codes (the number of occurrences is in brackets)
c("T814XXA (280)", "I638 (267)", "A047 (133)", "I4820 (106)", "I4819 (87)", "K5660 (82)", "N479 (57)", "K565 (51)", "K353 (49)", "K3589 (40)")
	
Wrong ICD version: total 3 ICD codes (the number of occurrences is in brackets)
c("I25110 (3)", "N10 (1)", "R4182 (1)")
	
Warning messages:
1: The ICD mentioned above matches to "NA" due to the format or other issues. 
2: "Wrong ICD format" means the ICD has wrong format 
3: "Wrong ICD version" means the ICD classify to wrong ICD version (cause the "icd10usingDate" or other issues) 
R>

ISSUES:
T814XXA is valid ICD10-CM code short version of T81.4XXA. T81.4XXA is a billable ICD code used to specify a diagnosis of infection following a procedure, initial encounter. A 'billable code' is detailed enough to be used to specify a medical diagnosis.

I25110 is a valid ICD10-CM code short version of I25.110. I25.110 is a billable ICD code used to specify a diagnosis of atherosclerotic heart disease of native coronary artery with unstable angina pectoris. A 'billable code' is detailed enough to be used to specify a medical diagnosis.

It would be better if user is allowed to select the ICD version to be used. The function argument - icd10usingDate appears to be very limiting.

Thanks for your time.

**Comment by yijutseng** [comment]
Hello @Kuroshiwo,

Thanks for reporting the issues. 

For the first T814XXA issue, we need to check the ICD table we used in the package. @ChunJuC could you please check the table and update it to the up-to-date version?

For the second issue, I understand that the "date" might be limiting in some situations.
If your data have the "tag" of the ICD version, you can use the attribute "icdVerColName" to set the version of the ICD used for the specific records. Please check the following document for further instruction.
https://dhlab-tseng.github.io/dxpr/reference/dxUniform.html  
@ChunJuC that would be great if you can add an example of using the "icdVerColName" attribute in the document.

Thank you,

YiJu

**Comment by mircyam** [comment]
Hi @Kuroshiwo,

Thanks for reporting.

For the T814XXA issue, T814XXA was reassigned to T8140XA on 2019 update of ICD-10.
Since _dxpr_ uses 2019 version of ICD-10, T814XXA is not available in our ICD table. 

As for the version issue, I re-write the sample datatable with a column recording ICD version (column name = Version), so it allows to manipulate data solely by version "tag" (rather than "date").
https://dhlab-tseng.github.io/dxpr/reference/dxUniform.html
Hope the instruction could help.


ICD-10 is still updating annually, so we are currently considering releasing a new version of _dxpr_ which uses newest ICD-10 version and includes CCSR into its function.

Thanks,

Chun-Ju

**Comment by Kuroshiwo** [comment]
Thank you very much yijutseng and ChunJuC for your prompt response to these issues. I will check your instructions and test the application. I will provide a response later.

Have the best of the day.

Kuroshiwo

**Comment by Kuroshiwo** [comment]
Hi @yijutseng and @ChunJuC,

R> sessionInfo()
R version 4.1.2 (2021-11-01)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 22000)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] lab_0.1.0         dxpr_0.3.0        forcats_0.5.1     stringr_1.4.0     dplyr_1.0.8      
 [6] purrr_0.3.4       readr_2.1.2       tidyr_1.2.0       tibble_3.1.6      ggplot2_3.3.5    
[11] tidyverse_1.3.1   data.table_1.14.2 lubridate_1.8.0   skimr_2.1.3      

I followed the suggestions in your previous response, however, errors were thrown as follows:

SCENARIOS 1: "icdVerColName = 10L" was included as argument to a function as stated in the package reference manual

R> ######### I - 1) DATA INTEGRATION AND FORMAT TRANSFORMATION
R> ## ICD to uniform short format
R> 
R> ICD_Short <- icdDxDecimalToShort(dxDataFile = sampleDxFile,
+                                  icdColName = ICD,
+                                  dateColName = Date,
+                                  icdVerColName = 10L,
+                                  icd10usingDate = "2015/10/01")
Error in `[.data.table`(setDT(dxDataFile), , dataCol, with = FALSE) : 
  column(s) not found: 10L
R> head(ICD_Short$ICD)
Error in head(ICD_Short$ICD) : object 'ICD_Short' not found
R> 
R> tail(ICD_Short$Error)
Error in tail(ICD_Short$Error) : object 'ICD_Short' not found
R> 
R> sampleDxFile$Decimal <- ICD_Short$ICD 
Error: object 'ICD_Short' not found
R> 
R> head(sampleDxFile)
           ID  ICD       Date Version
1: 1035537665 J441 2020-02-10      10
2: 1035537665 J441 2020-02-10      10
3: 1035537665 J441 2020-02-10      10
4: 1035537665 J441 2020-02-10      10
5: 1035537665 J441 2020-02-10      10
6: 1035537665 J441 2020-02-10      10
R>

SCENARIOS 2: Instead of "10L", "10" was used as "icdVerColName = 10". But an error was thrown.

R> ######### I - 1) DATA INTEGRATION AND FORMAT TRANSFORMATION
R> ## ICD to uniform short format
R> 
R> ICD_Short <- icdDxDecimalToShort(dxDataFile = sampleDxFile,
+                                  icdColName = ICD,
+                                  dateColName = Date,
+                                  icdVerColName = 10,
+                                  icd10usingDate = "2015/10/01")
Error in `[.data.table`(setDT(dxDataFile), , dataCol, with = FALSE) : 
  column(s) not found: 10
R> head(ICD_Short$ICD)
Error in head(ICD_Short$ICD) : object 'ICD_Short' not found
R> 
R> tail(ICD_Short$Error)
Error in tail(ICD_Short$Error) : object 'ICD_Short' not found
R> 
R> sampleDxFile$Decimal <- ICD_Short$ICD 
Error: object 'ICD_Short' not found
R> 
R> head(sampleDxFile)
           ID  ICD       Date Version
1: 1035537665 J441 2020-02-10      10
2: 1035537665 J441 2020-02-10      10
3: 1035537665 J441 2020-02-10      10
4: 1035537665 J441 2020-02-10      10
5: 1035537665 J441 2020-02-10      10
6: 1035537665 J441 2020-02-10      10
R>

SCENARIOS 3: The argument "icdVerColName = 10" was commented out and no errors were thrown.

Did I do something wrong?

Thanks for your time.

@Kuroshiwo

**Comment by mircyam** [comment]
Hi @Kuroshiwo,

According to your data, the icdVerColName is supposed to be **Version** rather than 10 nor 10L. If there is a column recorded ICD version, then 'icdVerColName' is the column name of that column. (In this case, column name is Version, and 10L is column value.)

Could you please change the argument input, and retry if this function works.

And we will considering revising our instructions to be more clear.

Thanks!

Chun-Ju

**Comment by Kuroshiwo** [comment]
Hi @ChunJuC

Again, thank you for your prompt response to my request.

Yes, the icdVerColName worked as you explained. And yes, please consider revising the instructions.

Now, I am waiting for switching to current revision of ICD-10 CM so I can use the package on real world data.

Thanks for your efforts.

Kuroshiwo

**Comment by mircyam** [comment]
Hello @Kuroshiwo,

We have released a new version of _dxpr_ :)
In this version, we collect all valid ICD-10-CM codes from 2019 to 2022.
And we also include CCSR classification method for ICD-10-CM.
May you kindly check the new release, and if there is any suggestion, please contact us anytime :)

Happy coding!

Chun-Ju

**Comment by Kuroshiwo** [comment]
Fantastic. Thanks for the information. I will check it out and provide a
feedback.

Enjoy the rest of your day.

Richard
