### ISSUE TITLE
groupIcdBasedOnCCS()

### ISSUE THREAD

**Issue by yijutseng** [DHLab-CGU/emr#4]
Error in select(ccsDxICD9_fullLabel, ICD, CCS_CATEGORY, CCS_CATEGORY_DESCRIPTION) : 
  找不到物件 'ccsDxICD9_fullLabel'

**Comment by amamagg** [comment]
換副檔名就可以柳

**Comment by yijutseng** [comment]
從什麼改什麼?紀錄一下或是連結COMMIT

**Comment by amamagg** [comment]
commit: 8f28b375f4ab83547192c1b63b4ad408e03a415d
把副檔名 rds ->rda就可以了
