### ISSUE TITLE
groupIcdBasedOnComorbid()

### ISSUE THREAD

**Issue by yijutseng** [DHLab-CGU/emr#5]
執行速度很慢，改掉for迴圈試試看
https://github.com/DHLab-CGU/emr/blob/master/R/groupIcdBasedOnComorbid.R

另外
AHRQ, Charlson and Elixhauser Comorbidity
這三個方法加上reference連結以及用法表（像是輸入時要用ahrq）

輸出很奇怪，明明是多人資料
`
DxDataFile <- data.frame(ID=c("A","A","B"),
                         ICD=c("6929","V433","I350"),
                         Date=as.Date(c("2013-03-31","2013-01-29","2016-03-10")),
                         stringsAsFactors = F)
groupIcdBasedOnComorbid(DxDataFile, ID, ICD, Date, "2016-01-01", ahrq, N, T)
`
輸出卻只有一列
`  CHF Valvular PHTN PVD HTN HTNcx Paralysis NeuroOther Pulmonary DM DMcx
1   0        2    0   0   0     0         0          0         0  0    0
  Hypothyroid Renal Liver PUD HIV Lymphoma Mets Tumor Rheumatic Coagulopathy
1           0     0     0   0   0        0    0     1         0            0
  Obesity WeightLoss FluidsLytes BloodLoss Anemia Alcohol Drugs Psychoses
1       0          0           0         0      0       0     0         0
  Depression
1          0`

**Comment by amamagg** [comment]
1. commit 4db462bdf40b276e372c53e39083b2b3ca954b36
1)移除for loop, 使用icd package的 comorbidity list(已轉成dataframe放在data)
2)解決不同ID的人共病症一起計算的問題 
```
DxDataFile <- data.frame(ID=c("A","A","B","B"),
                          ICD=c("40201","V433","I350","I050"),
                          Date=as.Date(c("2013-03-31","2013-01-29","2016-03-10","2016-03-10")),
                          stringsAsFactors = FALSE)
groupIcdBasedOnComorbid(DxDataFile, ID, ICD, Date, "2016-01-01", ahrq, N, F)

ID CHF Valvular PHTN PVD HTN HTNcx Paralysis NeuroOther Pulmonary DM DMcx Hypothyroid Renal Liver PUD HIV Lymphoma Mets Tumor Rheumatic
1  A   1        1    0   0   0     1         0          0         0  0    0           0     0     0   0   0        0    0     0         0
2  B   0        2    0   0   0     0         0          0         0  0    0           0     0     0   0   0        0    0     0         0
  Coagulopathy Obesity WeightLoss FluidsLytes BloodLoss Anemia Alcohol Drugs Psychoses Depression
1            0       0          0           0         0      0       0     0         0          0
2            0       0          0           0         0      0       0     0         0          0
```
2. Group by Date: 若相同ID同一天有相同comorbidity的, 不列入累計
commit a8c994527707412e1787e3549b6edf22b9b4a2ab
```
groupIcdBasedOnComorbid(DxDataFile, ID, ICD, Date, "2016-01-01", ahrq, N, T)
  ID CHF Valvular PHTN PVD HTN HTNcx Paralysis NeuroOther Pulmonary DM DMcx Hypothyroid Renal Liver PUD HIV Lymphoma Mets Tumor Rheumatic Coagulopathy
1  A   1        1    0   0   0     1         0          0         0  0    0           0     0     0   0   0        0    0     0         0            0
2  B   0        1    0   0   0     0         0          0         0  0    0           0     0     0   0   0        0    0     0         0            0
  Obesity WeightLoss FluidsLytes BloodLoss Anemia Alcohol Drugs Psychoses Depression
1       0          0           0         0      0       0     0         0          0
2       0          0           0         0      0       0     0         0          0
```
