### ISSUE TITLE
載入emr的訊息

### ISSUE THREAD

**Issue by yijutseng** [DHLab-CGU/emr#6]
使用 `library(emr)`出現下列訊息:

Attaching package: ‘emr’

The following object is masked _by_ ‘.GlobalEnv’:

    ccsDxICD9

應該是有不必要的資料? 再做微調即可

**Comment by amamagg** [comment]
剛剛請茹芳測試沒複製出一樣的問題 但如果install跟library一起按會安裝失敗
![91622](https://user-images.githubusercontent.com/37056305/44255006-3b80d500-a237-11e8-93d1-fee2fa614dab.jpg)
