### ISSUE TITLE
groupIcdBasedOnPhecode

### ISSUE THREAD

**Issue by Hulu0201** [DHLab-CGU/emr#8]
![image](https://user-images.githubusercontent.com/25901016/44560518-c0fa0d00-a782-11e8-8938-2a42abc0fa26.png)

'icd_' prefixed functions have been replaced with either ICD-9 or ICD-10 specific functions, which have an 'icd9_' or 'icd10_' prefix, or lost their prefix altogether.

**Comment by amamagg** [comment]
icd pkg的 message
![image](https://user-images.githubusercontent.com/37056305/45197305-09412100-b293-11e8-8e5a-cabcb589e602.png)

**Comment by yijutseng** [comment]
之前決議要自己做mapping table，應該可避免使用icd package轉換，就不會有這個錯誤訊息?

**Comment by amamagg** [comment]
對 但剛好查到就記錄一下XD

**Comment by amamagg** [comment]
上傳柳, 拿掉icd package了, 也改了相關有用到這些功能的function
icd format轉換的code需要公開嗎(?
commit 2700c03c014219cf542b1b96ac7bd456da1dce08

**Comment by yijutseng** [comment]
一併公開好了

**Comment by amamagg** [comment]
已上傳
commit 4ca7c1ca599164af1b4c9a59057079d6c61cf335
